=== inside-hakumai/TsukubaGradChecker/ref/requirement_schema.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://insidehakumai.net/ns/requirement">

    <xsd:element name="requirement">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="MS" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="FSM" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="GFS_common" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="GFS_related" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="sumNumber" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="required" type="xsd:float" minOccurs="1" maxOccurs="1"/>
                            <xsd:element name="elective" type="xsd:float" minOccurs="1" maxOccurs="1"/>
                            <xsd:element name="free" type="xsd:float" minOccurs="1" maxOccurs="1"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="MS" type="outerGroup"/>
    <xsd:element name="FSM" type="outerGroup"/>
    <xsd:element name="GFS_common" type="outerGroup"/>
    <xsd:element name="GFS_related" type="outerGroup"/>

    <xsd:complexType name="outerGroup">
        <xsd:sequence>
            <xsd:element ref="required" minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="elective" minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="free" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="required" type="innerGroup"/>
    <xsd:element name="elective" type="innerGroup"/>
    <xsd:element name="free" type="innerGroup"/>

    <xsd:complexType name="innerGroup">
        <xsd:sequence>
            <xsd:element name="number" type="xsd:float" minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="unit" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="determined" type="dtmAttr" use="optional"/>
        <xsd:attribute name="addup" type="xsd:string" use="optional"/>
    </xsd:complexType>
    
    <xsd:simpleType name="dtmAttr">
        <xsd:restriction>
            <xsd:enumeration value="true"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="unit">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="match" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="number" type="numberElem" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
            <xsd:attribute name="type" type="typeAttr" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="numberElem">
        <xsd:choice>
            <xsd:element name="fixed" type="xsd:float" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="range">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="minimum" type="xsd:float" minOccurs="1" maxOccurs="1"/>
                        <xsd:element name="maximum" type="xsd:float" minOccurs="1" maxOccurs="1"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
    </xsd:complexType>


    <xsd:simpleType name="typeAttr">
        <xsd:restriction>
            <xsd:enumeration value="single"/>
            <xsd:enumeration value="multiple"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== inside-hakumai/TsukubaGradChecker/ref/coins_26_software.xml
<?xml version="1.0" encoding="utf-8"?>
<requirement
        xmlns="http://insidehakumai.net/ns/requirement"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://insidehakumai.net/ns/requirement requirement_schema.xsd">
   <MS>
      <required determined="true">
         <number>34</number>
         <unit type="single">
            <name>コンピュータリテラシ</name>
            <match>^(GB10615|GB10625)$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>プログラミング入門A</name>
            <match>^GB10664$</match>
            <number>1</number>
         </unit>
         <unit type="single">
            <name>プログラミング入門B</name>
            <match>^GB10684$</match>
            <number>3</number>
         </unit>
         <unit type="single">
            <name>情報科学概論I</name>
            <match>^GB10981$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>情報科学概論II</name>
            <match>^GB10991$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>データ構造とアルゴリズム</name>
            <match>^GB11931$</match>
            <number>3</number>
         </unit>
         <unit type="single">
            <name>データ構造とアルゴリズム実験</name>
            <match>^(GB11926|GB11936|GB11946)$</match>
            <number>1.5</number>
         </unit>
         <unit type="single">
            <name>システムプログラミング序論</name>
            <match>^GB11954$</match>
            <number>3</number>
         </unit>
         <unit type="single">
            <name>情報科学基礎実験</name>
            <match>^GB10754$</match>
            <number>1</number>
         </unit>
         <unit type="single">
            <name>論理回路</name>
            <match>^GB10804$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>論理回路実験</name>
            <match>^GB12016$</match>
            <number>1.5</number>
         </unit>
         <unit type="single">
            <name>ソフトウェアサイエンス実験A</name>
            <match>^GB26403$</match>
            <number>3</number>
         </unit>
         <unit type="single">
            <name>ソフトウェアサイエンス実験B</name>
            <match>^GB26503$</match>
            <number>3</number>
         </unit>
         <unit type="single">
            <name>卒業研究A</name>
            <match>^GB19948$</match>
            <number>3</number>
         </unit>
         <unit type="single">
            <name>卒業研究B</name>
            <match>^GB19958$</match>
            <number>3</number>
         </unit>
      </required>
      <elective>
         <number>42</number>
         <unit type="multiple">
            <name>主専攻共通科目</name>
            <match>^(GB20|GB30|GB40|GB42101)</match>
            <number>12</number>
         </unit>
         <unit type="multiple">
            <name>GB1で始まる授業科目・GAで始まる科目</name>
            <match>^(GB1|GA)</match>
            <number>12</number>
         </unit>
         <unit type="multiple">
            <name>GB3で始める授業科目</name>
            <match>^GB3</match>
            <number>10</number>
         </unit>
         <unit type="multiple">
            <name>GB2、GB3又はGB4で始まる授業科目</name>
            <match>^(GB2|GB3|GB4)</match>
            <number>8</number>
         </unit>
      </elective>
      <free>
         <number>4</number>
         <unit type="multiple">
            <name>GBで始まる授業科目（専門基礎科目の選択科目で掲げられている科目を含み、GB0で始まる科目を除く） / 情報学群で開設する学群共通の授業科目（GAで始まる科目）</name>
            <match>^(GA|(?!GB0).*(?=GB).*$)</match>
            <number>4</number>
         </unit>
      </free>
   </MS>
   <FSM>
      <required determined="true">
         <number>16</number>
         <unit type="single">
            <name>線形代数I</name>
            <match>^(GB10114|GB10124)$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>線形代数II</name>
            <match>^(GB10214|GB10224)$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>解析学I</name>
            <match>^(GB10314|GB10324)$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>解析学II</name>
            <match>^(GB10414|GB10424)$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>離散構造</name>
            <match>^(GB10914|GB10924)$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>電磁気学</name>
            <match>^GB11404$</match>
            <number>2</number>
         </unit>
         <unit type="single">
            <name>シミュレーション物理</name>
            <match>^GB11514$</match>
            <number>1</number>
         </unit>
         <unit type="single">
            <name>専門語学A</name>
            <match>^GB19401$</match>
            <number>1.5</number>
         </unit>
         <unit type="single">
            <name>専門語学B</name>
            <match>^GB19501$</match>
            <number>1.5</number>
         </unit>
      </required>
      <elective>
         <number>8</number>
         <unit type="multiple">
            <name>解析学III /  複素関数論 / コンピュータ数学 / 確率論 / 力学 /  技術英語 / 情報特別演習I / 情報特別演習II / Mathematics for Computer Science</name>
            <match>^(GB10504|GB11701|GB11814|GB11601|GB11214|GB13212|GB13312|GB13322|GB13604)$</match>
            <number>8</number>
         </unit>
      </elective>
      <free>
         <number>0</number>
      </free>
   </FSM>
   <GFS_common>
      <required>
         <number>16.5</number>
         <unit type="multiple">
            <name>総合科目I</name>
            <match>^(11|12|13)</match>
            <number>2</number>
         </unit>
         <unit type="multiple">
            <name>総合科目II</name>
            <match>^(1A|1B|1C)</match>
            <number>6</number>
         </unit>
         <unit type="multiple">
            <name>体育</name>
            <match>^2</match>
            <number>3</number>
         </unit>
         <unit type="multiple">
            <name>第1外国語</name>
            <match>^31</match>
            <number>5.5</number>
         </unit>
      </required>
      <elective>
         <number>0</number>
      </elective>
      <free addup="「基礎科目(共通科目)の自由科目」と「基礎科目(関連科目)の自由科目」で合計5.5単位">
         <number>5.5</number>
         <unit type="multiple">
            <name>自由科目I・II</name>
            <match>^(11|12|13|1A|1B|1C)</match>
            <number>
               <range>
                  <minimum>0</minimum>
                  <maximum>3</maximum>
               </range>
            </number>
         </unit>
         <unit type="multiple">
            <name>体育</name>
            <match>^2</match>
            <number>
               <range>
                  <minimum>0</minimum>
                  <maximum>1</maximum>
               </range>
            </number>
         </unit>
         <unit type="multiple">
            <name>外国語</name>
            <match>^3</match>
            <number>
               <range>
                  <minimum>0</minimum>
                  <maximum>4.5</maximum>
               </range>
            </number>
         </unit>
         <unit type="multiple">
            <name>芸術</name>
            <choices>
               <match>^4</match>
            </choices>
            <number>
               <range>
                  <minimum>0</minimum>
                  <maximum>1</maximum>
               </range>
            </number>
         </unit>
         <unit type="multiple">
            <name>国語</name>
            <match>^5</match>
            <number>
               <range>
                  <minimum>0</minimum>
                  <maximum>2</maximum>
               </range>
            </number>
         </unit>
      </free>
   </GFS_common>
   <GFS_related>
      <required>
         <number>0</number>
      </required>
      <elective>
         <number>0</number>
      </elective>
      <free addup="「基礎科目(共通科目)の自由科目」と「基礎科目(関連科目)の自由科目」で合計5.5単位">
         <number>5.5</number>
         <unit type="multiple">
            <name>GB0で始まる科目 / 他学群・他学類の授業科目 / 特設自由科目 / 博物館に関する科目</name>
            <match>(^GB0|^(?!(GB|GA)).*$|^8|^99)</match>
            <number>
               <range>
                  <minimum>0</minimum>
                  <maximum>5.5</maximum>
               </range>
            </number>
         </unit>
      </free>
   </GFS_related>
   <sumNumber>
      <required>66.5</required>
      <elective>50</elective>
      <free>9.5</free>
   </sumNumber>
</requirement>
